[CmdletBinding()]
param(
    [string]$Version = (Get-Content -LiteralPath (Join-Path $PSScriptRoot '..\VERSION') -Raw).Trim()
)

$ErrorActionPreference = 'Stop'

$projectRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$releaseRoot = Join-Path $projectRoot 'release'
$product = "LeafBlowerRevolutionCE-$Version"
$calculatorStage = Join-Path $releaseRoot "_stage-$product-Calculator"
$sourceStage = Join-Path $releaseRoot "_stage-$product-Source"
$calculatorZip = Join-Path $releaseRoot "$product-Calculator.zip"
$sourceZip = Join-Path $releaseRoot "$product-Source.zip"

function Assert-ProjectChild([string]$Path) {
    $full = [System.IO.Path]::GetFullPath($Path)
    $prefix = $projectRoot.TrimEnd('\') + '\'
    if (-not $full.StartsWith($prefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to operate outside the project: $full"
    }
}

function Reset-Stage([string]$Path) {
    Assert-ProjectChild $Path
    if (Test-Path -LiteralPath $Path) {
        Remove-Item -LiteralPath $Path -Recurse -Force
    }
    New-Item -ItemType Directory -Path $Path -Force | Out-Null
}

function Copy-RequiredFile([string]$Source, [string]$Destination) {
    if (-not (Test-Path -LiteralPath $Source -PathType Leaf)) {
        throw "Required release file is missing: $Source"
    }
    $parent = Split-Path -Parent $Destination
    if ($parent) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    Copy-Item -LiteralPath $Source -Destination $Destination -Force
}

function Copy-RequiredTree([string]$Source, [string]$Destination) {
    if (-not (Test-Path -LiteralPath $Source -PathType Container)) {
        throw "Required source directory is missing: $Source"
    }
    Copy-Item -LiteralPath $Source -Destination $Destination -Recurse -Force
}

function Write-Manifest([string]$Root, [string]$Title) {
    $lines = @(
        $Title
        "Version: $Version"
        'Generated by tools/package-release.ps1'
        ''
        'Relative path | Bytes'
        '--------------|------'
    )
    $files = Get-ChildItem -LiteralPath $Root -Recurse -File |
        Where-Object { $_.Name -notin @('MANIFEST.txt', 'SHA256SUMS.txt') } |
        Sort-Object FullName
    foreach ($file in $files) {
        $relative = [System.IO.Path]::GetRelativePath($Root, $file.FullName).Replace('\', '/')
        $lines += "$relative | $($file.Length)"
    }
    Set-Content -LiteralPath (Join-Path $Root 'MANIFEST.txt') -Value $lines -Encoding utf8
}

function Write-Hashes([string]$Root) {
    $lines = @()
    $files = Get-ChildItem -LiteralPath $Root -Recurse -File |
        Where-Object { $_.Name -ne 'SHA256SUMS.txt' } |
        Sort-Object FullName
    foreach ($file in $files) {
        $relative = [System.IO.Path]::GetRelativePath($Root, $file.FullName).Replace('\', '/')
        $hash = (Get-FileHash -LiteralPath $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
        $lines += "$hash  $relative"
    }
    Set-Content -LiteralPath (Join-Path $Root 'SHA256SUMS.txt') -Value $lines -Encoding ascii
}

New-Item -ItemType Directory -Path $releaseRoot -Force | Out-Null
Reset-Stage $calculatorStage
Reset-Stage $sourceStage

$runtimeRoot = Join-Path $projectRoot 'vendor\ce-libraries-v15.0'
$runtimeFiles = Join-Path $runtimeRoot 'files\clibs'

# Calculator/user package. The five calculator files are kept at the ZIP root.
Copy-RequiredFile (Join-Path $projectRoot 'bin\LBRCE.8xp') (Join-Path $calculatorStage 'LBRCE.8xp')
foreach ($name in @('libload.8xv', 'fileioc.8xv', 'graphx.8xv', 'keypadc.8xv')) {
    Copy-RequiredFile (Join-Path $runtimeFiles $name) (Join-Path $calculatorStage $name)
}
foreach ($name in @('README.md', 'INSTALL.txt', 'RELEASE_NOTES.md', 'CHANGELOG.md', 'LICENSE')) {
    Copy-RequiredFile (Join-Path $projectRoot $name) (Join-Path $calculatorStage $name)
}
foreach ($name in @('FEATURE_MATRIX.md', 'ARCHITECTURE.md', 'TESTING.md', 'TEST_RESULTS.txt',
                    'LICENSES.md', 'ASSET_MANIFEST.csv', 'GENERATED_FILES.md', 'RESEARCH_SOURCES.md')) {
    Copy-RequiredFile (Join-Path $projectRoot "docs\$name") (Join-Path $calculatorStage "docs\$name")
}
New-Item -ItemType Directory -Path (Join-Path $calculatorStage 'third_party') -Force | Out-Null
foreach ($name in @('LICENSE_CE_LIBRARIES.txt', 'LICENSE_LIBLOAD_LGPL-3.0.txt', 'LICENSE_GPL-3.0.txt')) {
    Copy-RequiredFile (Join-Path $runtimeRoot $name) (Join-Path $calculatorStage "third_party\$name")
}
Write-Manifest $calculatorStage "$product calculator release manifest"
Write-Hashes $calculatorStage

# Complete source package. Build products and the release staging tree are intentionally excluded.
foreach ($name in @('makefile', 'README.md', 'BUILDING.md', 'INSTALL.txt', 'RELEASE_NOTES.md',
                    'CHANGELOG.md', 'LICENSE', 'VERSION')) {
    Copy-RequiredFile (Join-Path $projectRoot $name) (Join-Path $sourceStage $name)
}
foreach ($name in @('src', 'tests', 'docs', 'tools', 'vendor')) {
    Copy-RequiredTree (Join-Path $projectRoot $name) (Join-Path $sourceStage $name)
}
Write-Manifest $sourceStage "$product complete source manifest"
Write-Hashes $sourceStage

foreach ($zip in @($calculatorZip, $sourceZip)) {
    Assert-ProjectChild $zip
    if (Test-Path -LiteralPath $zip) {
        Remove-Item -LiteralPath $zip -Force
    }
}
Compress-Archive -Path (Join-Path $calculatorStage '*') -DestinationPath $calculatorZip -CompressionLevel Optimal
Compress-Archive -Path (Join-Path $sourceStage '*') -DestinationPath $sourceZip -CompressionLevel Optimal

# Convenient unzipped copies beside the archives.
foreach ($name in @('LBRCE.8xp', 'libload.8xv', 'fileioc.8xv', 'graphx.8xv', 'keypadc.8xv')) {
    Copy-RequiredFile (Join-Path $calculatorStage $name) (Join-Path $releaseRoot $name)
}
Copy-RequiredFile (Join-Path $calculatorStage 'MANIFEST.txt') (Join-Path $releaseRoot 'CALCULATOR_MANIFEST.txt')
Copy-RequiredFile (Join-Path $calculatorStage 'SHA256SUMS.txt') (Join-Path $releaseRoot 'CALCULATOR_SHA256SUMS.txt')

$topHashTargets = @(
    'LBRCE.8xp', 'libload.8xv', 'fileioc.8xv', 'graphx.8xv', 'keypadc.8xv',
    "$product-Calculator.zip", "$product-Source.zip"
)
$topHashes = foreach ($name in $topHashTargets) {
    $file = Join-Path $releaseRoot $name
    $hash = (Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash.ToLowerInvariant()
    "$hash  $name"
}
Set-Content -LiteralPath (Join-Path $releaseRoot 'SHA256SUMS.txt') -Value $topHashes -Encoding ascii

Write-Output $calculatorZip
Write-Output $sourceZip
